M48
; DRILL file {KiCad 9.0.1} date 2025-07-18T21:26:47+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-07-18T21:26:47+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0728
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X1.2144Y-7.0545
X1.2144Y-7.2455
T2
X1.0951Y-7.0427
X1.0951Y-7.2573
M30
